### ISSUE TITLE
Uraninite tag

### ISSUE THREAD

**Issue by YellowDoctor** [aurilisdev/Nuclear-Science#17]
Why can't uranium ore be tag?

I wanted to do it myself with the help of a datapack, but I couldn't find a yellow cake recipe for an example. 
And as a result, I did not find any recipe in the chemical extractor in the mod files. 
Where can they be located?

**Comment by aurilisdev** [comment]
"Why can't uranium ore be tag?"
In the newest code it is in fact a tag
