### ISSUE TITLE
Crash on dedicated server when nuclear reactor meltsdown

### ISSUE THREAD

**Issue by ranenvious** [aurilisdev/Nuclear-Science#27]
Behaviour:
When running Nuclear Science on a dedicated server the server crashes due to a ticking block entity exception whenever a reactor melts down.

1. Start server 
2. Join server
3. Place down a Fission Reactor Core
4. Place in 4 highly enriched uranium fuel rods
5. Wait...
6. It should crash.

Expected behavior:
The fission core should detonate and create a moderately large crater, (about as big as an applied energistics meteor site)

Log:
[crash-2021-10-23_04.52.39-server.txt](https://github.com/aurilisdev/Nuclear-Science/files/7402560/crash-2021-10-23_04.52.39-server.txt)

Version information:
    Client:
        MC : 16.5
        Forge: 36.2.8
        Mods: 2 (Electrodynamics and Nuclear Science)
        Java : jdk-14.0.2
    Server:
        MC : 16.5
        Forge: 36.2.8
        Mods: 2 (Electrodynamics and Nuclear Science)
        Java : jdk-14.0.2

**Comment by aurilisdev** [comment]
Has been fixed in the newest version which hsant been released yet
