### ISSUE TITLE
CurseForge Issues Link leads to 404 Not Found page

### ISSUE THREAD

**Issue by NielsPilgaard** [aurilisdev/Nuclear-Science#3]
Hi there o/

The CurseForge Issues link on Nuclear Science leads to the GitHub 404 Not Found page, because issues is very a capital i
Correct url: https://github.com/aurilisdev/Nuclear-Science/issues
Current url: https://github.com/aurilisdev/Nuclear-Science/Issues

**Comment by aurilisdev** [comment]
Thank you for notifying me 👍🏻
