### ISSUE TITLE
Missing or Removed Feature?

### ISSUE THREAD

**Issue by DariusSG** [aurilisdev/Nuclear-Science#30]
On your wiki `https://wiki.aurilis.dev/nuclear-science/nuclearscience-machines/fusion-reactor-core/`, It stated "This process requires deuterium and tritium which, you can produce in the chemical extractor and the fission reactor. To input these, you can either pump them in using item transfer blocks like hoppers or right-click the machine with a stack of either."

In the game, only right-clicking works. Pumping in the items did not work. I even tried using click machine, item user, etc but to no avail.
Is this intended or did you forget to add this and related code?
`addComponent(new ComponentInventory(this).size(2).faceSlots(Direction.UP, 0).faceSlots(Direction.DOWN, 1))`

**Comment by aurilisdev** [comment]
Yeah it hasn't been implemented yet in this version.
