### ISSUE TITLE
Transparent hand and Forcefield Crash?...

### ISSUE THREAD

**Issue by gmnovakrc** [aurilisdev/Nuclear-Science#38]
-MC 1.7.10
Latest 1.7.10 version of
-PhysicaCore-1.7.10-1.5.6-3
-Physica Nuclear Physics 1.5.7
-PhysicaForcefield-1.7.10-1.5.6-4

Making a modpack and eventual server to go along with it, private for friends only. 
There's a decent amount of mods, I can provide a list if needed.
Installed Core 1st, no problems, then tried to add Forcefield and got this crash.
[crash-2021-11-25_01.11.13-client.txt](https://github.com/aurilisdev/Nuclear-Science/files/7601176/crash-2021-11-25_01.11.13-client.txt)
Then added Nuclear Physics which made the crash go away, I'm guessing because it added the item in the crash report.

But then this happened.
![2021-11-25_02 43 54](https://user-images.githubusercontent.com/74471865/143402674-7fc2cc26-7f5e-41d8-b89b-3a5396e300e8.png)

If you need any other info please let me know.

**Comment by aurilisdev** [comment]
Dont know why this happens but 1.7 isnt supported anymore so this wont be fixed if its a bug
