### ISSUE TITLE
JEI Crash

### ISSUE THREAD

**Issue by oliverrook** [aurilisdev/Nuclear-Science#47]
Whenever I attempt to use JEI to view Particle Acceleration recipes, I get a crash to desktop.
Crash log:
[crash-2021-12-31_11.16.04-client.txt](https://github.com/aurilisdev/Nuclear-Science/files/7796619/crash-2021-12-31_11.16.04-client.txt)

**Comment by aurilisdev** [comment]
Was fixed now.
