### ISSUE TITLE
[Suggestion] Radiation disable/enable switch

### ISSUE THREAD

**Issue by ArchieBeepBoop** [aurilisdev/Nuclear-Science#52]
Hello there! Been running this mod for a bit but as a server manager I'd like to know if it would be possible to add a toggle switch for radiation from electrodynamics/nuclear science given how soon enough more mods that add that as a mechanic will be showing up on curse and I'd like to decide which one gets to stay active.

I couldn't find any configuration files in the config directory or serverconfig directory for the world that is currently running, so I thought it would be best to simply ask for such a feature.

Thank you!

**Comment by aurilisdev** [comment]
Its in the defaultconfigs directory and this may be added in the future
