### ISSUE TITLE
Rendering Overlay Crash Nuclear_Science-1.16.5-0.4.0-1

### ISSUE THREAD

**Issue by Enterprise12nx01** [aurilisdev/Nuclear-Science#64]
Getting a crash launching the game in 1.16.5 pointing towards Nuclear Science
https://zerobin.net/?7f58302aeff47d4a#tg2YnkZ/YEZ0/Bz2dq3DbYLFqxpBzgcTacWvi7EzLX0=

**Comment by aurilisdev** [comment]
1.16 is no longer supported i am sorry :/
