### ISSUE TITLE
1.16.5 - MSR freeze plug and molten salt supplier will not receive power

### ISSUE THREAD

**Issue by benjaming20** [aurilisdev/Nuclear-Science#66]
I am on the latest 1.16.5 version of the mod (along with electrodynamics) and the Freeze Plus and Molten Salt Supplier will not receive power.
Voltage is 120V
Enough Wattage is available (it isn't even draining the batteries at all
Batteries are charged and orientated correctly
Config is default
LiFi-ThF4-UF4 pellets are present in the supplier and FLiNaK in the freeze plug
This is happening with no other mods installed on the latest forge version
![2023-02-07_19 34 51](https://user-images.githubusercontent.com/82496993/217193719-e2d173e8-5d8a-4e1b-89b4-36dc93dee4b2.png)

**Comment by aurilisdev** [comment]
1.16 is no longer supported i am sorry :/
