### ISSUE TITLE
Crash on dedicated server in 1.19.2

### ISSUE THREAD

**Issue by seancrain** [aurilisdev/Nuclear-Science#68]
I have a particle accelerator injector placed on the server by itself, as I haven't started construction on the whole thing yet.

Updating to the latest versions of Electrodynamics and Nuclear Science cause this crash to occur:

[crash-2023-02-15_08.53.36-server.txt](https://github.com/aurilisdev/Nuclear-Science/files/10744308/crash-2023-02-15_08.53.36-server.txt)

I'm not sure if this is a crash in Electrodynamics or in Nuclear Science, but the block is from Nuclear Science.

**Comment by aurilisdev** [comment]
Yes if you want to update you have to reset your world. Sorry about this but alot of stuff changed backend
