### ISSUE TITLE
Server crash after reactor explosion

### ISSUE THREAD

**Issue by Reincarnaciya** [aurilisdev/Nuclear-Science#75]
When the "Fission Reactor Core" block explodes, the entire server crashes, when the block disappears, everything falls out of it. Crash log below.

MC ver 1 16 5

[crash-2023-03-26_17.03.21-server.txt](https://github.com/aurilisdev/Nuclear-Science/files/11071827/crash-2023-03-26_17.03.21-server.txt)

**Comment by aurilisdev** [comment]
1.16 is no longer supported
