### ISSUE TITLE
Mark Electrodynamics as a required dependency on Curseforge

### ISSUE THREAD

**Issue by 04Slash** [aurilisdev/Nuclear-Science#9]
Currently, it's not marked as a required dependency. This means if you download the mod through a launcher that supports downloading from Curseforge the dependency will not be downloaded and the game will crash due to lacking the dependency. Adding Electrodynamics as a dependency will make these launchers download both Electrodynamics and Nuclear Science when Nuclear Science is downloaded. This will also let anyone who's on Curseforge know that this mod has a dependency.

Thank you.

**Comment by aurilisdev** [comment]
Will do
